### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by FinchNie** [SongW-SW/GLITTER#1]
Thanks for your great work. May I know when the code will be updated?

**Comment by SongW-SW** [comment]
Hi, thanks for your concern! We are still cleaning the code, and hopefully we will update in next month. Sorry for the inconvenience!

**Comment by XsLangley** [comment]
Hi, may I know whether the code is ready or not?

**Comment by XsLangley** [comment]
> Hi, thanks for your concern! We are still cleaning the code, and hopefully we will update in next month. Sorry for the inconvenience!

Hi, may I know whether the code is ready or not?

**Comment by JiaruiFeng** [comment]
Hi, I also want to know if the code is ready. I want to include your method as a baseline. Thank you!

**Comment by SongW-SW** [comment]
Hi, thanks for your patience! Sorry for the inconvenience! We are glad to announce that we will update the code in two weeks.

**Comment by SongW-SW** [comment]
Hi folks, thanks for your interest! We have uploaded the data file and code for our work. Thank you again for your patience!
